#!/usr/bin/env python3
"""POC write-isolation checker (BEH-018 §6 / scheme A).

Detects poc-track leakage into Trunk write surfaces:
  src/**  include/**  tests/**

Usage:
  python3 spec/meta/tools/ndf_poc_isolation.py check --topic <topic>
  python3 spec/meta/tools/ndf_poc_isolation.py check --all-topics
  python3 spec/meta/tools/ndf_poc_isolation.py check --workspace
  python3 spec/meta/tools/ndf_poc_isolation.py check --topic <topic> --workspace

Exit 1 if any hard finding. Reports go to stdout (or --report tmp/...).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

import ndf_report_io as rio  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
POC = ROOT / "poc"
TOOL = "spec/meta/tools/ndf_poc_isolation.py"
DEFAULT_REPORT = "tmp/ndf-poc-isolation.md"

FORBIDDEN_PREFIXES = ("src/", "include/", "tests/")


@dataclass
class Finding:
    severity: str
    kind: str
    topic: str
    message: str
    loc: str = ""


def git(*args: str) -> tuple[int, str]:
    try:
        p = subprocess.run(
            ["git", *args],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            check=False,
        )
        out = (p.stdout or "") + (("\n" + p.stderr) if p.stderr else "")
        return p.returncode, out.strip()
    except FileNotFoundError:
        return 127, "git not found"


def list_topics() -> list[str]:
    if not POC.is_dir():
        return []
    return sorted(
        d.name
        for d in POC.iterdir()
        if d.is_dir() and (d / "ndf" / "TOPIC.md").is_file()
    )


def is_forbidden(path: str) -> bool:
    rel = path.lstrip("./")
    return any(rel == p[:-1] or rel.startswith(p) for p in FORBIDDEN_PREFIXES)


def commits_touching_topic(topic: str) -> list[str]:
    code, out = git("log", "--format=%H", "--", f"poc/{topic}")
    if code != 0 or not out:
        return []
    return [ln.strip() for ln in out.splitlines() if ln.strip()]


def commit_files(sha: str) -> list[str]:
    code, out = git("diff-tree", "--no-commit-id", "--name-only", "-r", sha)
    if code != 0 or not out:
        return []
    return [ln.strip() for ln in out.splitlines() if ln.strip()]


def workspace_changed_files() -> list[str]:
    files: list[str] = []
    for args in (
        ["diff", "--name-only", "HEAD"],
        ["diff", "--name-only", "--cached"],
        ["ls-files", "--others", "--exclude-standard"],
    ):
        code, out = git(*args)
        if code == 0 and out:
            files.extend(ln.strip() for ln in out.splitlines() if ln.strip())
    # dedupe preserve order
    seen: set[str] = set()
    out_list: list[str] = []
    for f in files:
        if f not in seen:
            seen.add(f)
            out_list.append(f)
    return out_list


def check_topic_commits(topic: str) -> list[Finding]:
    findings: list[Finding] = []
    for sha in commits_touching_topic(topic):
        bad = [f for f in commit_files(sha) if is_forbidden(f)]
        if not bad:
            continue
        short = sha[:7]
        code, subj = git("log", "-1", "--format=%s", sha)
        subject = subj if code == 0 else ""
        findings.append(
            Finding(
                "error",
                "trunk_write_in_poc_commit",
                topic,
                f"commit {short} touches poc/{topic} and Trunk write surface: "
                f"{', '.join(bad[:8])}"
                + (f" (+{len(bad) - 8} more)" if len(bad) > 8 else ""),
                loc=f"git:{short}",
            )
        )
        findings[-1].message += f" | {subject}" if subject else ""
    return findings


def check_workspace(topic: str | None) -> list[Finding]:
    findings: list[Finding] = []
    bad = [f for f in workspace_changed_files() if is_forbidden(f)]
    if not bad:
        return findings
    label = topic or "(workspace)"
    findings.append(
        Finding(
            "error",
            "trunk_write_in_workspace",
            label,
            "working tree / index changes under Trunk write surface "
            f"(src|include|tests): {', '.join(bad[:12])}"
            + (f" (+{len(bad) - 12} more)" if len(bad) > 12 else ""),
            loc="workspace",
        )
    )
    return findings


def build_report(findings: list[Finding], topics: list[str]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    errors = [f for f in findings if f.severity == "error"]
    lines = [
        "# NDF poc isolation report",
        "",
        f"> Generated by `{TOOL}` at {now}",
        "",
        f"- topics: {', '.join(topics) if topics else '(workspace-only)'}",
        f"- hard_errors: {len(errors)}",
        "",
        "## Issue index",
        "",
    ]
    if not findings:
        lines.append("_(none)_")
        lines.append("")
    else:
        lines.append("| # | sev | kind | topic | message | loc |")
        lines.append("|--:|-----|------|-------|---------|-----|")
        for i, f in enumerate(findings, 1):
            msg = f.message.replace("|", "\\|")
            lines.append(
                f"| {i} | {f.severity} | `{f.kind}` | `{f.topic}` | {msg} | `{f.loc}` |"
            )
        lines.append("")
    lines.append(
        "> Scheme A ([[BEH-018]] §6): poc MUST NOT write `src/`/`include/`/`tests/`; "
        "copy into `poc/<topic>/` before editing. Read-only link to unmodified Trunk is OK."
    )
    lines.append("")
    return "\n".join(lines)


def cmd_check(args: argparse.Namespace) -> int:
    findings: list[Finding] = []
    topics: list[str] = []

    if args.all_topics:
        topics = list_topics()
    elif args.topic:
        topics = [args.topic]
    elif not args.workspace:
        print("need --topic, --all-topics, and/or --workspace", file=sys.stderr)
        return 2

    for t in topics:
        if not (POC / t / "ndf" / "TOPIC.md").is_file():
            print(f"warning: missing binder poc/{t}/ndf/TOPIC.md", file=sys.stderr)
        findings.extend(check_topic_commits(t))

    if args.workspace:
        findings.extend(check_workspace(args.topic))

    try:
        report_path = rio.resolve_report_path(args.report, DEFAULT_REPORT)
    except rio.ReportPathError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    text = build_report(findings, topics)
    written = rio.write_report(report_path, text)
    errors = sum(1 for f in findings if f.severity == "error")
    print(f"# ndf_poc_isolation  topics={topics or ['(workspace)']}")
    print(f"summary: {errors} error(s)")
    for f in findings:
        print(f"- [{f.severity}] `{f.kind}` ({f.topic}) {f.message}")
        if f.loc:
            print(f"  loc: `{f.loc}`")
    if written is not None:
        print(f"wrote report: {written}")
    return 1 if errors else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("check", help="Detect Trunk write-surface leakage from POC work")
    g = p.add_mutually_exclusive_group(required=False)
    g.add_argument("--topic", help="POC topic under poc/")
    g.add_argument("--all-topics", action="store_true")
    p.add_argument(
        "--workspace",
        action="store_true",
        help="also flag dirty/untracked files under src|include|tests",
    )
    p.add_argument(
        "--report",
        default=DEFAULT_REPORT,
        help=f"Markdown report path (default: {DEFAULT_REPORT}); '-' = stdout only",
    )
    p.set_defaults(func=cmd_check)
    args = ap.parse_args()
    if args.cmd == "check" and not (args.topic or args.all_topics or args.workspace):
        print("need --topic, --all-topics, and/or --workspace", file=sys.stderr)
        return 2
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
